# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
# This is an example of using VeraDemoDotNet test application with the Veracode Static Pipeline scanner.  A Veracode subscription is required.

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  condition: false

- task: PowerShell@2
  displayName: Veracode Package
  env:
    VERACODE_API_KEY_ID: $(VERACODE_API_ID)
    VERACODE_API_KEY_SECRET: $(VERACODE_API_KEY)
  inputs:
    targetType: 'inline'
    script: |
      $veracodeWrapperUrl = "https://tools.veracode.com/veracode-cli/install.ps1"

      # Enable Powershell to run scripts
      Set-ExecutionPolicy AllSigned -Scope Process -Force

      # Download the Veracode CLI
      $ProgressPreference = "silentlyContinue"; iex ((New-Object System.Net.WebClient).DownloadString($veracodeWrapperUrl))

      # Run autopackage, placing files in verascan
      veracode package --source ./ --output ./verascan --trust

- task: PowerShell@2
  displayName: Veracode Policy Scan
  inputs:
    targetType: 'inline'
    script: |
      # Define variables
      $veracodeWrapperUrl = "https://tools.veracode.com/integrations/API-Wrappers/CSharp/bin/VeracodeCSharpAPI.zip"
      $veracodeWrapperZip = "VeracodeCSharpAPI.zip"
      $veracodeWrapperDir = "VeracodeCSharpAPI"
      $veracodeAppID = "Verademo DotNet AutoPackage"
      $veracodeSandboxID = "YOUR_VERACODE_SANDBOX_ID"

      # Download Veracode C# API wrapper
      Invoke-WebRequest -Uri $veracodeWrapperUrl -OutFile $veracodeWrapperZip

      # Extract Veracode C# API wrapper
      Expand-Archive -Path $veracodeWrapperZip -DestinationPath $veracodeWrapperDir

      # Navigate to Veracode C# API wrapper directory
      cd $veracodeWrapperDir

      # Run Veracode static analysis using the wrapper
      .\VeracodeC#API.exe -action uploadandscan `
          -vid $(VERACODE_API_ID) `
          -vkey $(VERACODE_API_KEY) `
          -appname $veracodeAppID `
          -createprofile true `
          -criticality High `
          -version $(Build.BuildId) `
          -selectedpreviously true `
          -scantimeout 30 `
          -filepath './verascan'
